### ISSUE TITLE
Error installing Foundation package

### ISSUE THREAD

**Issue by kdmcguire** [albertinad/brackets-bower#13] opened 2014-07-14 10:31 UTC
I'm trying to install Zurb's Foundation package, and getting an error every time. I have:

1. Installed Git from https://msysgit.github.io/
2. Restarted both Brackets first and then the machine
3. Created a directory first in case packages can only be added to a currently active project.

No luck! I'm not sure how to find out more info about the error for you, unfortunately.

**Comment by albertinad** [comment] 2015-02-03 01:42
Hi @kieranmcguire , Is this bug still reproducible with the new version 0.2.0 available at the registry? If the error persists, please click on Debug, Show Developers Tools and paste the content of the console here. Thanks!

**Comment by albertinad** [comment] 2015-03-07 03:14
Hi @kdmcguire , I'm can't reproduce it. I will close the issue, if you notice that this bug happens again, please re open it :)
Thanks!

**Closed by albertinad** 2015-03-07 03:14 UTC
Labels: bug
